name: Build and Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH folDer
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Remote Server via SSH
        run: |
          echo "cd /home/runneruser/hello-next
          docker compose down
          docker compose up -d --build" | ssh -o StrictHostKeyChecking=no -p 1894 ${{ secrets.SSH_USERNAME }}@${{ secrets.REMOTE_HOST }}
